before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64

  goarm:
    - '7'

  ignore:
    - goos: windows
      goarch: 'arm'

  binary: '{{ .ProjectName }}'

checksum:
  algorithm: sha256

dockers:
  - &image-def
    image_templates:
      - fopina/{{.ProjectName}}:{{ .Version }}-amd64
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64,linux/arm64/v8
  - <<: *image-def
    image_templates:
      - fopina/{{.ProjectName}}:{{ .Version }}-arm64
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64/v8
  - <<: *image-def
    image_templates:
      - fopina/{{.ProjectName}}:{{ .Version }}-armv7
    goarch: arm
    goarm: '7'
    build_flag_templates:
      - --platform=linux/arm/v7

docker_manifests:
  - &manifest-def
    name_template: fopina/{{.ProjectName}}:{{ .Version }}
    image_templates:
      - fopina/{{.ProjectName}}:{{ .Version }}-armv7
      - fopina/{{.ProjectName}}:{{ .Version }}-arm64
      - fopina/{{.ProjectName}}:{{ .Version }}-amd64
  - <<: *manifest-def
    name_template: fopina/{{.ProjectName}}:latest
  - <<: *manifest-def
    name_template: ghcr.io/fopina/{{.ProjectName}}:latest
  - <<: *manifest-def
    name_template: ghcr.io/fopina/{{.ProjectName}}:{{ .Version }}
