name: 🔨 Build Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12.2
          args: --timeout 5m
          working-directory: .
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test .

      - name: Build
        run: go build .
