name: 🎉 Release Binary
on:
  create:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs: 
  release: 
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: "Set up Go"
        uses: actions/setup-go@v3
        with: 
          go-version: 1.19

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v3
        with: 
          args: "release --clean"
          version: latest
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - run: docker images

      - run: docker push fopina/gotlsproxy:predicted-armv7

      - run: docker push ghcir.io/fopina/gotlsproxy:predicted-armv7
